/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import crud.LibrosCRUD;
import crud.PrestamosCRUD;
import crud.UsuariosCRUD;
import db.MyConnection;
import entity.Libros;
import entity.Prestamos;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import entity.Usuarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author allexiusw
 */
public class ModuloPrestamos extends javax.swing.JDialog {

    /**
     * Creates new form ModuloLibros
     */
    public ModuloPrestamos() {
        setModal(true);
        initComponents();
        crearModelo();
        PrestamosCRUD p = new PrestamosCRUD(MyConnection.getConnection());
        ArrayList<Prestamos> rows = p.getPendientes();
        volcarDatos(rows);
        this.getRootPane().setDefaultButton(btnBuscar);
        btnBuscar.setVisible(false);
    }
    //@method crearModelo permite crear la estructura de la tabla
    public void crearModelo(){
        jTable1 = new JTable();
        jTable1.setModel(
            new DefaultTableModel(
                new Object[][]{},
                new String[]{"Fecha","Estado", "Libro", "Usuario", "Object"}
            )
        );
        jScrollPane1.setViewportView(jTable1);
        jTable1.removeColumn(jTable1.getColumn("Object"));
    }
    
    public void volcarDatos(ArrayList<Prestamos> rows){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        while(model.getRowCount()>0)model.removeRow(0);
        for(Prestamos row : rows){
            Object[] fila = {
                    row.getFecha(),
                    row.getEstado(), 
                    row.getNombreLibro(),
                    row.getNombreUsuario(),
                    row
            };
            model.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("Prestamos Pendientes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnDevolver.setText("Registrar Devolucion");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fecha", "Codigo de Usuario", "Codigo de Libro" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(btnDevolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevolver)
                    .addComponent(btnBuscar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        Prestamos us = (Prestamos) jTable1.getModel().getValueAt(
            jTable1.getSelectedRow(), 4
        );
        PrestamosCRUD pres = new PrestamosCRUD(MyConnection.getConnection());
        boolean state = pres.updateStateDevuelto(us);
        LibrosCRUD lib = new LibrosCRUD(MyConnection.getConnection());
        Libros mylib = new Libros(us.getIdLibro(), "", "", "", 0);
        boolean restado = lib.updateDevuelto(mylib);
        ArrayList rows = pres.getPendientes();
        volcarDatos(rows);
        if(state && restado){
            JOptionPane.showMessageDialog(this, "La devolución ha sido registrada");
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String text = txtBuscar.getText().toString();
        PrestamosCRUD pdao =  new PrestamosCRUD(MyConnection.getConnection());
        ArrayList<Prestamos> rows = new ArrayList<>();
        Prestamos p;
        if(text.isEmpty()){
            rows = pdao.getPendientes();
        }else{
            String option = jComboBox1.getSelectedItem().toString();
            switch(option){
                case "Fecha":
                    JOptionPane.showMessageDialog(this, "Opcion no disponible en este momento");
                    break;
                    
                /*case "Codigo de Libro":
                    String texto = JOptionPane.showInputDialog(this, "Ingrese el codigo de libro para general la consulta");
                    p = new Prestamos();
                    listado = udao.getByNombre(u);
                    break;
                
                case "DNI":
                    u = new Usuarios(null, null, text);
                    listado = udao.getByDNI(u);
                    break;*/
            }
        }
        /*if(listado.isEmpty()){
            JOptionPane.showMessageDialog(this, "No se encontraron coincidencias");
        }else{
            //volcarDatos(listado);
        }*/
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
